name: web_view_app
description: "건강해짐 애플리케이션"
version: 1.0.0+0
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^17.2.0
  permission_handler: ^11.3.1
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"