name: web_view_app
description: "건강해짐 애플리케이션"
version: 1.0.0+3
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^22.2.0
  permission_handler: ^12.0.3
  http: ^1.6.0
  flutter_secure_storage: ^10.3.1
  fluttertoast: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true