// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCvaGdXas6LuaCNPeZ9FMCNqhR5VbaL2U',
    appId: '1:793717607575:web:fa7d5b2f29130f3c87add2',
    messagingSenderId: '793717607575',
    projectId: 'solar-imprint-417411',
    authDomain: 'solar-imprint-417411.firebaseapp.com',
    storageBucket: 'solar-imprint-417411.appspot.com',
    measurementId: 'G-F501B0PBYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl9TuDJg677hHqs04PtNkpqVuwNYDmUMo',
    appId: '1:793717607575:android:e4ebe8db6574ea1587add2',
    messagingSenderId: '793717607575',
    projectId: 'solar-imprint-417411',
    storageBucket: 'solar-imprint-417411.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQrehsT00S9-EIDHn-eGBFyMSbDHp8mpc',
    appId: '1:793717607575:ios:153c1a34111e714787add2',
    messagingSenderId: '793717607575',
    projectId: 'solar-imprint-417411',
    storageBucket: 'solar-imprint-417411.appspot.com',
    iosBundleId: 'com.example.webViewApp.RunnerTests',
  );
}
